### ISSUE TITLE
vncsetup not working

### ISSUE THREAD

**Issue by chapeter** [csoukup/mustang-grove-pi#1]
When run the setup VNC doesn't seem to be working.  When I run the vncserver script I get the following:
./vncserver: 4: .: Can't open /lib/init/init-d-script

I tried to just create the init-d-script file...not sure whats suppose to be in there...when I do I get the following when I try to run /etc/init.d/vncserver start:

$ /etc/init.d/vncserver start
Usage: /etc/init.d/vncserver {start|stop}

**Comment by chapeter** [comment]
I fixed it on my setup by commenting out:
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
#if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
#    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script

**Comment by csoukup** [comment]
Thanks @chapeter.  I'll update the README with my assumptions for the install, and the expected results after the install.

I tested on a clean Rasbian Jessie image and hadn't tested any other OS types.

**Comment by chapeter** [comment]
Yep, worked with jessie.  I was still on Wheezy.  Thanks!
